apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-react
  template:
    metadata:
      labels:
        app: redis-react
    spec:
      containers:
        - name: redis-react
          image: yasmine77/front
          imagePullPolicy: Always  
          ports:
            - containerPort: 8080
         

