version: '3.8'

services:
  # Service Redis
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Exposer le port Redis sur 6379
    networks:
      - redis-network
    restart: always

  # Service serveur Node.js
  server:
    image: node-redis-server:latest  # Remplacez par le nom de votre image Node.js
    container_name: node-server
    ports:
      - "3000:3000"  # Exposer le port de l'application Node.js
    environment:
      REDIS_URL: "redis://redis:6379"  # URL de connexion à Redis
    depends_on:
      - redis
    networks:
      - redis-network
    restart: always

networks:
  redis-network:
    driver: bridge

